---
title: "Chicago_Map_HBH"
output: html_document
date: "2022-10-07"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library("sf")
library("ggplot2")
library ("plotly")
library ("dplyr")
library ("readr")
```

```{r mapsetup, echo=FALSE}
# ward boundaries from chicago data portal
chicago_map <- read_sf("community_areas.geojson")

# latitude and longitude of HBH sites
hbh_data <- read.csv("hbh_locations.csv")
hbh_df <- data.frame(hbh_data)

# amend data frame to classify each column
hbh_df$Lat <- as.numeric(hbh_df$Lat)
hbh_df$Long <- as.numeric(hbh_df$Long)
hbh_df$Site <- as.character(hbh_df$Site)

# amend data frame to include name of each site
hbh_df <- hbh_df %>% mutate(desc = paste(`Site`, sep = "\n"))

# import chicago public health data csv
chicago_health <- read.csv("public_health_indicators.csv")

# amend public health data to classify wards
chicago_health <- chicago_health %>% mutate(area_num_1 = as.character(`Community.Area`))

# create new map from community areas and public health data
chicago_health_map <- left_join(chicago_map, chicago_health, by = "area_num_1")
```

```{r site info, echo=FALSE, warning=FALSE}
site_info <- ggplot() +
  geom_sf(data = chicago_map) + 
  labs(title = "Chicago Communities") +
  geom_point (data = hbh_df, aes(x = Long, y = Lat, text = desc)) +
  theme(axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank())

fig_1 <- ggplotly(site_info, tooltip = "desc")

fig_1
```

```{r infant mortality map, echo=FALSE, warning=FALSE}
infant_mortality_map <- ggplot() +
  geom_sf(data = chicago_health_map, aes(fill = Infant.Mortality.Rate)) +
  labs(title = "Infant Mortality in Chicago", fill = "Infant Mortality Rate") +
  scale_fill_continuous(type = "viridis") +
  geom_point (data = hbh_df, alpha = 8/10, aes(x = Long, y = Lat, text = desc)) +
  theme(axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank())

fig_2 <- ggplotly(infant_mortality_map, tooltip = "desc")

fig_2
  
```

```{r teen birth rate map, echo=FALSE, warning=FALSE}
teen_birth_rate_map <- ggplot() +
  geom_sf(data = chicago_health_map, aes(fill = Teen.Birth.Rate)) +
  labs(title = "Teen Births in Chicago", fill = "Teen Birth Rate") +
  scale_fill_continuous(type = "viridis") +
  geom_point (data = hbh_df, alpha = 8/10, aes(x = Long, y = Lat, text = desc)) +
  theme(axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank())

fig_3 <- ggplotly(teen_birth_rate_map, tooltip = "desc")

fig_3
  
```

```{r poverty level map, echo=FALSE, warning=FALSE}
poverty_level_map <- ggplot() +
  geom_sf(data = chicago_health_map, aes(fill = Below.Poverty.Level)) +
  labs(title = "Poverty in Chicago", fill = "% Below Poverty Level") +
  scale_fill_continuous(type = "viridis") +
  geom_point (data = hbh_df, alpha = 8/10, aes(x = Long, y = Lat, text = desc)) +
  theme(axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank())

fig_4 <- ggplotly(poverty_level_map, tooltip = "desc")

fig_4
  
```

```{r unemployment map, echo=FALSE, warning=FALSE}
unemployment_map <- ggplot() +
  geom_sf(data = chicago_health_map, aes(fill = Unemployment)) +
  labs(title = "Unemployment in Chicago", fill = "Unemployment Rate") +
  scale_fill_continuous(type = "viridis") +
  geom_point (data = hbh_df, alpha = 8/10, aes(x = Long, y = Lat, text = desc)) +
  theme(axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank())

fig_5 <- ggplotly(unemployment_map, tooltip = "desc")

fig_5
  
```
